model: &model
  name: mln
  num_classes: 21
  mol_params:
    h_dim: 2048
    use_bn: true
    k: 7
    sig_min: 1
    sig_max: 10
    mu_min: -2
    mu_max: 2
    share_sig: true
  backbone_params:
    name: resnet50
    pretrained: true
  checkpoint_path: ''

train: &train
  num_epochs: 200

  optimizer: &optimizer
    name: sgd
    lr: 0.01
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001

  optimizer1: &optimizer1
    name: sgd
    lr: 0.001
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001

  optimizer2: &optimizer2
    name: sgd
    lr: 0.001
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0001

  criterion: &criterion
    name: mace

  lr_schedule: &lr_schedule
    name: custom
    milestones: [20,40,60]
    gamma: 0.2

eval: &eval
  standard: accuracy

data: &data
  name: 'voc'
  root: 'data/VOCdevkit'
  batch_size: 64
  num_workers: 4
  num_full_sup: 10582

  transform: &transform
    image_size: 256
    train_crop_size: 224
    val_crop_size: 224
