model: &model
  name: mln
  num_classes: 200
  mol_params:
    h_dim: 2048
    use_bn: true
    k: 5
    sig_min: 1
    sig_max: 10
    mu_min: -2
    mu_max: 2
    share_sig: true
  backbone_params:
    name: resnet50
    pretrained: true
  checkpoint_path: ''

train: &train
  num_epochs: 200

  optimizer: &optimizer
    name: sgd
    lr: 0.01
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0005

  criterion: &criterion
    name: mace

  lr_schedule: &lr_schedule
    name: custom
    milestones: [30,60,90,120,150]
    gamma: 0.2

eval: &eval
  standard: accuracy

data: &data
  name: 'cub'
  root: 'data'
  batch_size: 64
  num_workers: 0

  transform: &transform
    image_size: 256
    crop_size: 224
